apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-controller
  labels:
    app: application-controller
    tier: controller
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      pod: application-controller
      tier: controller
  template:
    metadata:
      labels:
        pod: application-controller
        tier: controller
    spec:
      imagePullSecrets:
        - name: image-pull-secret
      containers:
        - name: simple-application
          image: bmekdboncloud.azurecr.io/application-controller:0.0.1
          ports:
            - containerPort: 5000
              name: controller
              protocol: TCP
          env:
          - name: CONTROLLER_PORT
            value: "5000"
