apiVersion: v1
kind: Service
metadata:
  name: application-controller
spec:
  selector:
    pod: application-controller
    tier: controller
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 5000
