apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: generic-application
  labels:
    app: generic-application
    tier: worker
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: worker
  template:
    metadata:
      labels:
        tier: worker
    spec:
      containers:
        - name: generic-application
          image: generic-application:0.0.1
