apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-application
  labels:
    app: simple-application
    tier: worker
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: worker
  template:
    metadata:
      labels:
        tier: worker
    spec:
      containers:
        - name: simple-application
          image: simple-application-logging:0.0.1
